name: Tests

on: push

jobs:
    ci:
      strategy:
        fail-fast: true
        matrix:
          python-version: [3.7, 3.8, 3.9]
          poetry-version: [1.1.11]
          os: [ubuntu-latest]
      runs-on: ${{ matrix.os }}
      steps:
        - uses: actions/checkout@v2
        - name: Set up Python ${{ matrix.python-version }}
          uses: actions/setup-python@v2
          with:
            python-version: ${{ matrix.python-version }}
        - name: Run image
          uses: abatilo/actions-poetry@v2.1.3
          with:
            poetry-version: ${{ matrix.poetry-version }}
        - name: Install dependencies
          run: poetry install
        - name: Style
          run: poetry run make lint
        - name: Test
          run: poetry run make test
